version: 2

sources:
  - name: raw_human_resources
    description: Dados brutos extraídos do modelo OLTP.
    schema: humanresources
    tables:
      - name: department
        description: "Description"

      - name: "employee"
        description: "Description"

      - name: "employeedepartmenthistory"
        description: "Description"

      - name: "employeepayhistory"
        description: "Description"

      - name: "jobcandidate"
        description: "Description"

      - name: "shift"
        description: "Description"

  - name: raw_person
    description: Dados brutos extraídos do modelo OLTP.
    schema: person
    tables:
      - name: emailaddress
        description: "Description"

      - name: password
        description: "Description"

      - name: person
        description: "Description"

      - name: personphone
        description: "Description"

      - name: phonenumbertype
        description: "Description"

      - name: stateprovince
        description: "Description"
